interface AkaObj {
    tokenId: number,
    ipfsHash: string,
    sales?: {
        swaps: {
            swapId: number,
            issuer: string,
            alias: string,
            akaObjAmount: number,
            xtzPerAkaObj: number,
        }[],
        auctions: {
            auctionId: number,
            issuer: string,
            alias: string,
            akaObjAmount: number,
            currentBidPrice: number,
            dueTime: number,
            auctionTitle: string,
        }[],
        bundles: {
            bundleId: number,
            issuer: string,
            alias: string,
            bundleAmount: number,
            akaObjAmount: number,
            xtzPerBundle: number,
            bundleTitle: string,
        }[],
        gachas: {
            gachaId: number,
            issuer: string,
            alias: string,
            akaObjRemain: number,
            xtzPerGacha: number,
            issueTime: number,
            cancelTime: number,
            gachaTitle: string,
        }[],
    },
    owners: { [key: string]: number },
    aliases: { [key: string]: string },
    totalAmount: number,
    tokenInfo: TokenInfo,
}

interface TokenInfo {
    name: string,
    description: string,
    tags: string[],
    frameColor?: string,
    symbol: string,
    artifactUri: string,
    displayUri: string,
    thumbnailUri: string,
    creators: string[],
    aliases: string[],
    formats: {
        uri: string,
        mimeType: string,
    }[],
    decimals: number,
    isBooleanAmount: boolean,
    shouldPreferSymbol: boolean,
    creatorShares: number[],
}