interface Auction {
    banned?: boolean,
    auctionId: number,
    tokenId: number,
    currentBidPrice: number,
    currentBidder: string,
    currentStorePrice: number,
    directPrice: number,
    dueTime: number,
    issuer: string,
    alias: string,
    metadata: PackMetadata,
    priceHistory: {
        bidPrice: number,
        bidder: string,
        alias: string,
        timestamp: number,
    }[],
    priceHistoryId: number,
    raisePercentage: number,
    startPrice: number,
    ipfsHash: string,
    tokenInfo?: TokenInfo,
}